### PR TITLE
Closes #475: Fix main thread CPU pegging

### LINKED ISSUE #475: Blocked main thread during async task
There is a bug since 1.0.7 where an async task is causing Firefox to peg CPU at 100% utilization on 1 thread or more (including the main thread).

It seems caused by an async task, potentially one introduced in #304

### PR DESCRIPTION
**Pull request by oyiptong**
This fixes the main thread CPU pegging issue.

Closes #475 
r? @rlr

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/481)

### CODE REVIEW

File: lib/ActivityStreams.js [hunk 1]
```diff
@@ -118,31 +112,31 @@ ActivityStreams.prototype = {
...
+          this._previewProvider.asyncSaveNewLinks(processedLinks);
           const cachedLinks = this._previewProvider.getCachedLinks(processedLinks);
           this.send(am.actions.Response("TOP_FRECENT_SITES_RESPONSE", cachedLinks, {append}), worker);
         });
         break;
       case am.type("RECENT_BOOKMARKS_REQUEST"):
         this._memoized.getRecentBookmarks(msg.data).then(links => {
           let processedLinks = this._previewProvider.processLinks(links);
-          this._previewProvider.saveNewLinks(processedLinks);
+          this._previewProvider.asyncSaveNewLinks(processedLinks);
```
Comment (rlr) [inline lib/ActivityStreams.js]: :+1: +1000 for the `async...()`

Comment (rlr) [inline lib/ActivityStreams.js]: (there probably should be a yield in front of this right? which is the bug I was looking at)

Comment (oyiptong) [inline lib/ActivityStreams.js]: Probably a `then` which encloses whatever needs to follow sequentially.

And yes, I didn't fix it because you want to take it on, right?

File: lib/ActivityStreams.js [hunk 2]
```diff
@@ -290,47 +281,69 @@ ActivityStreams.prototype = {
...
+
+      yield Promise.all(promises);
+      yield this._previewProvider.asyncSaveNewLinks(linksToSend);
+      this._populatingCache.preview = false;
+      Services.obs.notifyObservers(null, "activity-streams-previews-cache-complete", null);
+    }
   }),
 
   /**
+   * Set up preview cache to be repopulated every 6 hours
```
Comment (rlr) [inline lib/ActivityStreams.js]: This is only called from init. I would expect the timeout to be cleared and restarted every time the cache is populated.

Comment (oyiptong) [inline lib/ActivityStreams.js]: do you mean `this._previewCacheTimeoutID` ?

Comment (oyiptong) [inline lib/ActivityStreams.js]: The cache population function and the timeout have been decoupled in part so that they can be unit tested

Comment (rlr) [inline lib/ActivityStreams.js]: yeah. I would expect that to be cleared out every time the cache gets built. Then this function called again to reset it. Also, as it is right now, it gets set up once and never gets set again after being triggered.

Comment (rlr) [inline lib/ActivityStreams.js]: (so it really isn't periodic as it says it is)

Comment (rlr) [inline lib/ActivityStreams.js]: then it could work off of the `Services.obs.notifyObservers(null, "activity-streams-previews-cache-complete", null);` event

File: lib/ActivityStreams.js [hunk 3]
```diff
@@ -290,47 +281,69 @@ ActivityStreams.prototype = {
...
+   */
+  _startPeriodicBuildPreviewCache(previewCacheTimeout) {
+    if (previewCacheTimeout) {
+      // only set a timeout if a non-null value is provided otherwise this will
+      // effectively be an infinite loop
+      this._previewCacheTimeoutID = setTimeout(() => {
+        this._asyncBuildPreviewCache();
+        this._startPeriodicBuildPreviewCache(previewCacheTimeout);
```
Comment (rlr) [inline lib/ActivityStreams.js]: oh duh, i see it here lol

File: lib/ActivityStreams.js (hunk 2 above)
Comment (rlr) [inline lib/ActivityStreams.js]: nvm... then.. .i guess it could be fancier by resetting off the cache-complete event. but whatevs. it seems like we will be constantly rebuilding cache anyway while the user is active.

Comment (oyiptong) [inline lib/ActivityStreams.js]: It is periodic: there is a recursive call at line 341. We also test this: https://github.com/mozilla/activity-streams/pull/481/files#diff-afc7a0b5d5d8bab654f47ee7ac5fd5b7R68

Comment (oyiptong) [inline lib/ActivityStreams.js]: Oh, that test is a misnomer, it's not an invalidation, it's a repopulation. I'll rename it

File: lib/ActivityStreams.js [hunk 4]
```diff
@@ -443,22 +456,31 @@ ActivityStreams.prototype = {
...
+      this._appURLHider.uninit();
+      this._perfMeter.uninit();
+      this._memoizer.uninit();
+      this._populatingCache.places = false;
+      this._populatingCache.preview = false;
+    };
+
     switch (reason){
       // can be one of: uninstall/disable/shutdown/upgrade/downgrade
+      case "uninstall":
```
Comment (rlr) [inline lib/ActivityStreams.js]: this will never get called https://bugzilla.mozilla.org/show_bug.cgi?id=627432

Comment (rlr) [inline lib/ActivityStreams.js]: specifically comment 12 https://bugzilla.mozilla.org/show_bug.cgi?id=627432#c12

You might want to do `disable` instead?

Comment (oyiptong) [inline lib/ActivityStreams.js]: Oh! I didn't know "uninstall" is never called. Thank you!

File: test/test-ActivityStreams-async-preview-cleanup.js [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+  previewsCachePromise = makeCachePromise("previews");
+  let app = new ActivityStreams({previewCacheTimeout: 100});
+  yield placesCachePromise;
+  yield previewsCachePromise;
+
+  let expectedInvalidations = 3;
+  let previewsCountPromise = makeCountingCachePromise("previews", expectedInvalidations);
+  let numInvalidations = yield previewsCountPromise;
+
+  assert.equal(numInvalidations, expectedInvalidations, "preview cache successfully invalidated periodically");
```
Comment (rlr) [inline test/test-ActivityStreams-async-preview-cleanup.js]: cool!

**Comment by rlr** [comment]
awesome! sorry about the confusion. Async is hard before my 5th :coffee: :laughing: ... I'm going to play with it locally for sanity checking...

**Comment by rlr** [comment]
travis broke with latest push ^

Seems to be working better now. Is it faster or is it me? r+ w/ travis fix

**Comment by oyiptong** [comment]
hmm that failure is actually in karma. and it is intermittent. let me take a look

**Comment by oyiptong** [comment]
@k88hudson says the intermittent issue may have been fixed in 6fdef5d76f9d629cc62be329d333c826b9577447.

I'll merge and close
