### PR TITLE
fix(addon): #123 Fix include path to include hashes

### LINKED ISSUE #123: Add-on messaging doesn't work after refresh
After refreshing the page, messages no longer work with the following error in the console

```
Error: Couldn't find the worker to receive this message.
The script may not be initialized yet, or may already have been unloaded.
```

### PR DESCRIPTION
**Pull request by k88hudson**
This fixes a bug where if you reload the page, new workers don't get attached, and also properly removes workers when the tab is reloaded/closed

Fixes #123

### CODE REVIEW

**Comment by k88hudson** [comment]
@oyiptong @emtwo R?

File: test/test-setup.js [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+const PORT = 8099;
+const path = "/dummy-activitystreams.html";
+const url = `http://localhost:${PORT}${path}`;
+const otherUrl = `http://localhost:${PORT}/dummy-other.html`;
+
+let srv;
+let app;
+let openTabs;
+
+function beforeEach() {
```
Comment (oyiptong) [inline test/test-setup.js]: Use the addon sdk's before and after test methods

File: test/test-setup.js [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+  app = new ActivityStreams({pageURL: url});
+  openTabs = [];
+
+  function onOpen(tab) {
+    openTabs.push(tab);
+  }
+  tabs.on("open", onOpen);
+}
+
+function afterEachPromise() {
```
Comment (oyiptong) [inline test/test-setup.js]: Ditto

File: test/test-setup.js [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+  beforeEach();
+  yield new Promise(resolve => {
+    let worker;
+    function onReady(tab) {
+      if (tab.url === url) {
+        assert.equal(app.workers.size, 1);
+        worker = getFirstWorker();
+        worker.port.on("content-to-addon", msg => {
+          if (msg.type === "pagehide") {
+            assert.equal(app.workers.size, 0, "Worker should be unloaded when a new url is loaded in the tab");
```
Comment (oyiptong) [inline test/test-setup.js]: There might be a race condition here, depending on when the listener is registered. Might be better to listen to a tab event if we can then check the worker if posdible

File: test/test-setup.js [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+  beforeEach();
+  yield new Promise(resolve => {
+    function onReady(tab) {
+      if (tab.url === url) {
+        assert.equal(app.workers.size, 1, "Worker is loaded");
+      }
+      resolve();
+    }
+    tabs.open({url, onReady});
+  });
```
Comment (oyiptong) [inline test/test-setup.js]: Maybe a better test would be to have no tabs, test the number of workers (zero), open a new tab, test (one worker).

Same applies for other tests

File: test/test-setup.js (hunk 3 above)
Comment (oyiptong) [inline test/test-setup.js]: Hmm actually, I take that back. The activity streams object attaches the worker listener on init, and this listener should come second in the queue. One quick check of the port implementation would confirm.

The test then checks if page hide is sent or hangs, which is good

File: lib/ActivityStreams.js [hunk 5]
```diff
@@ -129,11 +129,17 @@ ActivityStreams.prototype = {
     // `this` here refers to the object instance
     this.workers = new Set();
     this._pagemod = new PageMod({
-      include: [this.options.pageURL],
+      include: [this.options.pageURL + "*"],
```
Comment (oyiptong) [inline lib/ActivityStreams.js]: :+1 finding this!

File: lib/ActivityStreams.js [hunk 6]
```diff
@@ -129,11 +129,17 @@ ActivityStreams.prototype = {
...
       contentScriptFile: data.url("content-bridge.js"),
       contentScriptWhen: "start",
-      attachTo: "top",
+      attachTo: ["existing", "top"],
       onAttach: worker => {
+
+        // This detaches workers on reload or closing the tab
+        worker.on("detach", () => {
```
Comment (oyiptong) [inline lib/ActivityStreams.js]: +1 :-)

File: test/test-setup.js [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+    if (tab.url === url) {
+      assert.equal(app.workers.size, 1, "Worker is loaded");
+    }
+    done();
+  }
+  assert.equal(app.workers.size, 0, "app.workers start at 0");
+  tabs.open({url, onReady});
+};
+
+exports["test removing worker on url change"] = function(assert, done) {
```
Comment (oyiptong) [inline test/test-setup.js]: why not generator style?

Comment (k88hudson) [inline test/test-setup.js]: there's not really a point to having a generator now since it's a single async function, it's less code/easier to read this way

Comment (k88hudson) [inline test/test-setup.js]: i'm happy to use it if you need yield more than one promise, but yeah, it's just not needed in this case

**Comment by k88hudson** [comment]
I noticed the add-on button wasn't getting destroyed, so I added that in as well with a separate commit. @oyiptong r?

**Comment by oyiptong** [comment]
r+ after CI is fixed

**Comment by pdehaan** [comment]
@k88hudson @oyiptong Is this ready to merge?

**Comment by oyiptong** [comment]
I think @k88hudson is working on this and should merge whenever she's ready
