### PR TITLE
fix(addon): #209 Save tab data in memory instead of simple storage and send notification on tab session completion.

### LINKED ISSUE #209: Tab tracking should be done in memory, not simple storage

### PR DESCRIPTION
**Pull request by emtwo**
Fixes #209

### CODE REVIEW

File: lib/TabTracker.js [hunk 1]
```diff
@@ -33,30 +34,32 @@ TabTracker.prototype = {
...
   },
 
   navigateAwayFromPage: function(tab) {
-    if (!ss.storage.tabData[tab.url][tab.id]) {
+    if (!this._tabData[tab.url][tab.id]) {
       // We're navigating away from an activity streams page that
       // didn't even load yet. Let's say it's been active for 0 seconds.
-      ss.storage.tabData[tab.url][tab.id] = {activations: [{startTime: Date.now(), totalTime: 0}]};
+      this._tabData[tab.url][tab.id] = {activations: [{startTime: Date.now(), totalTime: 0}]};
+      DataSender.send(DataSender.TAB_SESSION_COMPLETE, this._tabData);
```
Comment (oyiptong) [inline lib/TabTracker.js]: Can you please send the tabData as part of an observer notification?

This gives us flexibility as far as how the data ends up in the data sender.

File: lib/TabTracker.js [hunk 2]
```diff
@@ -33,30 +34,32 @@ TabTracker.prototype = {
...
       return;
     }
     let lastElement = this.getLastActivation(tab);
     if (lastElement && lastElement.startTime) {
       lastElement.totalTime = (Date.now() - lastElement.startTime) / 1000;
     }
+    DataSender.send(DataSender.TAB_SESSION_COMPLETE, this._tabData);
```
Comment (oyiptong) [inline lib/TabTracker.js]: as above

File: lib/DataSender.js [hunk 3]
```diff
@@ -0,0 +1,14 @@
+const DataSender = {
```
Comment (oyiptong) [inline lib/DataSender.js]: A more evocative name would be:

`TelemetrySender`

File: lib/TabTracker.js [hunk 4]
```diff
@@ -33,30 +34,32 @@ TabTracker.prototype = {
   },
 
   getLastActivation: function(tab) {
-    if (!ss.storage.tabData[tab.url] || !ss.storage.tabData[tab.url][tab.id]) {
+    if (!this._tabData[tab.url] || !this._tabData[tab.url][tab.id]) {
```
Comment (oyiptong) [inline lib/TabTracker.js]: Since we will only ever have one active tab at any given time, it makes sense to make `tab.id` a property of `_tabData` as a sibling of `tab.url`.

File: lib/TabTracker.js [hunk 5]
```diff
@@ -33,30 +34,32 @@ TabTracker.prototype = {
...
     }
+    DataSender.send(DataSender.TAB_SESSION_COMPLETE, this._tabData);
   },
 
   logReady: function(tab) {
     if (this.isActivityStreamsURL(tab.url)) {
-      if (!ss.storage.tabData[tab.url][tab.id]) {
-        ss.storage.tabData[tab.url][tab.id] = {activations: []};
+      if (!this._tabData[tab.url][tab.id]) {
+        this._tabData[tab.url][tab.id] = {activations: []};
```
Comment (oyiptong) [inline lib/TabTracker.js]: `activations` may not be useful anymore, since we'll only have one

File: lib/TabTracker.js [hunk 6]
```diff
@@ -76,7 +79,7 @@ TabTracker.prototype = {
 
   logActivate: function(tab) {
     if (this.isActivityStreamsURL(tab.url)) {
-      ss.storage.tabData[tab.url][tab.id].activations.push({startTime: Date.now()});
+      this._tabData[tab.url][tab.id].activations.push({startTime: Date.now()});
```
Comment (oyiptong) [inline lib/TabTracker.js]: `startTime` should probably be a first-level object to tabData as well

File: lib/TabTracker.js (hunk 4 above)
Comment (oyiptong) [inline lib/TabTracker.js]: We should still do sanity checks for `url` and `id` whenever an event occurs.

File: lib/DataSender.js (hunk 3 above)
Comment (oyiptong) [inline lib/DataSender.js]: Or were you thinking of implementing the `Services.obs.notifyObservers` function call here?

**Comment by oyiptong** [comment]
feeback+

File: lib/TabTracker.js (hunk 6 above)
Comment (emtwo) [inline lib/TabTracker.js]: I'm going to change this entire structure to align with what we talked about today.This pull request was just for switching to using memory rather than simple storage and for notifications.

Comment (oyiptong) [inline lib/TabTracker.js]: Ah, ok, thanks for the heads up. Will you change the structure in another PR?

Comment (emtwo) [inline lib/TabTracker.js]: yes, I just separated them so I can have something review-able by eod and I'll get to the structure change in another PR.

**Comment by emtwo** [comment]
@oyiptong I made the notification changes and updated the module name to Telemetry sender. I'd like to address your other comments in a separate PR if that's ok with you?

**Comment by oyiptong** [comment]
r+ after there is at least one test of the observer notifications
