### PR TITLE
fix (addon): #646 do not throw exception on invalid uri component

### LINKED ISSUE #646: Bookmark urls containing % cause Bookmarks view to not render
I have some bookmarks saved but one of them is causing an error in the add-on code: `URIError: malformed URI sequence PreviewProvider.js:124:79`

I looked through my bookmarks and the problem was my search Bugzilla bookmark: `https://bugzilla.mozilla.org/buglist.cgi?quicksearch=%s`

If I removed the `%` from the bookmark URL then the Bookmarks view in Activity Streams works great.

### PR DESCRIPTION
**Pull request by rlr**
r? @oyiptong @k88hudson

Fixes #646

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/654)

### CODE REVIEW

File: lib/PreviewProvider.js [hunk 1]
```diff
@@ -110,6 +110,17 @@ PreviewProvider.prototype = {
   },
 
   /**
+    * A decodeURIComponent that doesn't throw on invalid URI components
+    */
+  _safeDecodeURIComponent(str) {
+    try {
+      return decodeURIComponent(str);
+    } catch (e) {
+      return str;
```
Comment (rlr) [inline lib/PreviewProvider.js]: maybe should return empty string instead?

Comment (oyiptong) [inline lib/PreviewProvider.js]: AFAICS `decodeURIComponent` fails when there's an invalid URL passed.

Is there a situation where it is failing on valid URL's?

For instance, this passes: `decodeURIComponent("foo://example.com/bar?baz=quux&foo=bar%20baz")`

But this doesn't: `decodeURIComponent("foo://example.com/bar?baz=quux&foo=bar%baz")`

This is rightly so, because the URL is invalid

Comment (k88hudson) [inline lib/PreviewProvider.js]: @oyiptong and I discussed this, let's verify that the URLs which come back are *not* URI encoded, and if that is the case, we shouldn't be decoding at all

Comment (rlr) [inline lib/PreviewProvider.js]: good point. It doesnt seem like they are encoded. I'll remove

**Comment by rlr** [comment]
^^ updated to remove the decoding.

**Comment by k88hudson** [comment]
Looks good to me R+ (this should pass if you rebase)

**Comment by rlr** [comment]
squashed, rebased and waiting on travis to give green light.
