### PR TITLE
fix(activityfeed): Use fallback hostname if page doesnt have title

### LINKED ISSUE #248: Odd UI in Activity Stream when a page doesn't have a usable title
During random browsing I noticed that certain sites don't seem to have a title (whether they were an image, JSON, or a redirect), that you end up with just a mis-aligned looking link.

new_tab

Not sure  how/if we want to fix that, but thought I'd file it for giggles so we can see if we want to fall back to a `provider_name` or `provider_display` or something (assuming it isn't too redundant).

1. http://embedly-proxy.dev.mozaws.net/extract?urls=https://raw.githubusercontent.com/mozilla/activity-streams/master/dev-prefs.json

  ```js
{
  "https://raw.githubusercontent.com/mozilla/activity-streams/master/dev-prefs.json": {
    provider_display: "raw.githubusercontent.com",
    provider_name: "Raw",
    provider_url: "https://raw.githubusercontent.com",
    title: null,
    type: "text",
    url: "https://raw.githubusercontent.com/mozilla/activity-streams/master/dev-prefs.json",
    // ....
  }
}
```

2. http://embedly-proxy.dev.mozaws.net/extract?urls=https://christianalfoni.github.io/react-webpack-cookbook/Structuring-configuration.html

  ```js
{
  "https://christianalfoni.github.io/react-webpack-cookbook/Structuring-configuration.html": {
    provider_display: "christianalfoni.github.io",
    provider_name: "Christianalfoni",
    provider_url: "https://christianalfoni.github.io",
    title: null,
    type: "html",
    url: "https://christianalfoni.github.io/react-webpack-cookbook/Structuring-configuration.html",
  }
}
```

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #248

### CODE REVIEW

File: content-src/components/ActivityFeed/ActivityFeed.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ const ActivityFeedItem = React.createClass({
   },
   render() {
     const site = this.props;
-    const title = site.title;
+    const title = site.title || site.provider_display || site.parsedUrl.hostname;
```
Comment (rlr) [inline content-src/components/ActivityFeed/ActivityFeed.js]: :+1:

**Comment by k88hudson** [comment]
LGTM R+ :dancer:
