### PR TITLE
fix(content): #558 Dont clear rows for error append actions

### LINKED ISSUE #558: Bug 1266741 - "Just now" area goes blank and history timeline is interrupted when fetching old visited websites
via https://bugzilla.mozilla.org/show_bug.cgi?id=1266741
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.11

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The used Firefox profile is an old one with a lot of data and history.
- Install the Activity Stream add-on on the old profile

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on "See more activity" button from Timeline.
4. Wait for the content to load.
5. Click on "See more activity" button from Timeline.
6. Repeat steps 3 to 5 multiple times.

[Expected results]:
Every time "See more activity" button is clicked, old history is fetched and displayed in timeline.

[Actual results]:
- After a few tries the entire content  of just now ares is removed
- If you wait for a few seconds, the "Just now" area is repopulated with content, but the previous displayed items are no longer visible. Instead of them the content requested at the last "Show more" operation is now displayed at the beginning of the section.
timeline content

### PR DESCRIPTION
**Pull request by k88hudson**
Right now, if an append-type response with an error is received (e.g. a timeout), we actually clear the whole rows value, which isn't what we want.

This PR changes the behaviour to leave `rows` unchanged for append-type errors.

We also might want to adjust the timeout maybe?

Fixes #558 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/576)

### CODE REVIEW

**Comment by pdehaan** [comment]
> Coverage decreased (-91.003%) to 0.0%

**Comment by k88hudson** [comment]
@pdehaan yeah something's up with coveralls, I'm investigating now

**Comment by k88hudson** [comment]
@pdehaan jks i DELETED ALL THE TESTS

😈 😈 😈 😈 😈 😈 😈 😈

**Comment by k88hudson** [comment]
Damn you coveralls

**Comment by k88hudson** [comment]
Anyway, this is the summary from travis

```

=============================== Coverage summary ===============================
Statements   : 86.12% ( 546/634 )
Branches     : 76.71% ( 168/219 )
Functions    : 75.9% ( 63/83 )
Lines        : 91% ( 526/578 )
================================================================================
```

r? @rlr

File: content-src/reducers/SetRowsOrError.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    const meta = action.meta || {};
+    switch (action.type) {
+      case am.type(requestType):
+        state.isLoading = true;
+        break;
+      case am.type(responseType):
+        state.init = true;
+        state.isLoading = false;
+        if (action.error) {
+          state.rows = meta.append ? prevState.rows : [];
```
Comment (rlr) [inline content-src/reducers/SetRowsOrError.js]: from what I can tell, this is the only line that changed here. 👍

**Comment by rlr** [comment]
I restarted travis but they passed for me locally. R+
