### PR TITLE
fix(content): #177 Handle filtering of URLs and embedly data more gracefully

### LINKED ISSUE #177: Better filtering of site data
My current output looks like this:
new_tab_and_new_tab

You can see in the developer tools output that I'm getting some errors back from the embedly proxy where we get an `error_code` and `error_message` (mainly because there is no way for a proxy to resolve my "localhost" and "ideatown.dev" testing domains.

new_tab_and_new_tab

We probably want to filter out any results from the embedly proxy when we encounter a [response](http://docs.embed.ly/docs/extract#response-attributes) with the following properties:
- `error_code`
- `error_message`

For the latter two, it seems like embedly will return a `type` of "error" which is probably easiest to filter on.
For more information, see http://docs.embed.ly/docs/extract#error-codes.

### PR DESCRIPTION
**Pull request by k88hudson**
Fixes #177 by filtering out error responses. I also added some URL filtering for long URLs (>100 characters), localhost, and non-http[s] protocols

### CODE REVIEW

**Comment by k88hudson** [comment]
@oyiptong @pdehaan or @rlr R?

File: content-src/lib/filters.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+        result = false;
+      }
+    });
+    return result;
+  };
+}
+
+const URL_FILTERS = [
+  item => !!item.url,
+  item => item.url && item.url.length < 100,
```
Comment (pdehaan) [inline content-src/lib/filters.js]: Why an arbitrary URL length limit?

For example, why wouldn't I want to see URLs like: `https://github.com/k88hudson/activity-streams/commit/eceda0e47e9f4a810bddf089e08c7b04dea1688f` (don't actually fact check the length, it's only like 94 chars, but you get the point).

Also, bonus points for making the 100 magic number a `const` at the top of the file, like `MAX_URL_LEN` or whatever.

File: content-src/lib/filters.js [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+  item => /^https?:/i.test(item.url),
+  item => !(/^https?:\/\/localhost/i.test(item.url))
```
Comment (pdehaan) [inline content-src/lib/filters.js]: Not sure if we need to add a `\/` at the end of localhost here. Something tells me that this would incorrectly catch on domains like "http://localhost-is-cool.com"

Also, do we want to try and filter out loopback URLs like "127.0.0.1" and "0.0.0.0"?

File: content-src/lib/filters.js (hunk 1 above)
Comment (k88hudson) [inline content-src/lib/filters.js]: This is kind of a stop-gap until we implement the POST-style requests. I'll make a note

File: content-src/lib/filters.js (hunk 2 above)
Comment (k88hudson) [inline content-src/lib/filters.js]: :+1:

Comment (pdehaan) [inline content-src/lib/filters.js]: Actually, the loopback URLs would probably be handled by `DATA_FILTERS` below.

**Comment by k88hudson** [comment]
@pdehaan ok, what do you think about this?

**Comment by pdehaan** [comment]
Looks great!
But I'm still seeing the one edge case of I have a hacked site in my /etc/hosts for ideatown.dev which is showing up in my Top Sites (but it should have returned an error from the embedly proxy, I would assume).

new_tab_and_nightly_and_nightly

**Comment by k88hudson** [comment]
weird! hmm...

**Comment by k88hudson** [comment]
Aha, found the issue!

**Comment by k88hudson** [comment]
@pdehaan ok, can you see if this fixes it?

**Comment by pdehaan** [comment]
### FAN-TAS-TIC!

Looks good to me. I'm seeing some other issues w/ duplicate child keys, but I think it's probably unrelated and something we can address in a future PR. :+1:

(Note that I only have 5 Top Sites and 2 Spotlight sites)
new_tab

**Comment by k88hudson** [comment]
Yes, we should definitely sort out that de-duping
