### PR TITLE
fix(favicon): Add activity-stream SVG favicon

### LINKED ISSUE #354: Add Activity Stream Favicon
In either the tab for activity stream or if you pin the tab, there isn't a favicon. would be nice to have :)

screen shot 2016-03-23 at 3 12 47 pm

### PR DESCRIPTION
**Pull request by pdehaan**
**Current output:**
add-ons_manager_and__googleads_jade_ _mysite_ _mysite

Fixes #354 

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/activity-streams/520)

### CODE REVIEW

File: bin/generate-html.js [hunk 1]
```diff
@@ -7,13 +7,13 @@ const defaults = {
...
-  return `
-<!doctype html>
-<html lang=en-us>
+  return `<!doctype html>
+<html lang="en-us">
   <head>
     <meta charset="utf-8">
     <title>${options.title}</title>
     <link rel="stylesheet" href="${options.baseUrl}main.css" />
+    <link rel="icon" type="image/svg+xml" href="${options.baseUrl}img/glyph-activityStream-16.svg">
```
Comment (pdehaan) [inline bin/generate-html.js]: Browser support isn't great for SVG favicons, but we only care about The Firefox (which has outstanding support). http://caniuse.com/#feat=link-icon-svg

**Comment by k88hudson** [comment]
R+
